---
- shell: docker exec -it ec2-user_jenkins_master_1 cat {{ path_initial_admin }}
  register: admin_password
- set_fact: admin_password={{ admin_password.stdout }}
- shell: java -jar jenkins-cli.jar -auth admin:{{ admin_password }} -s http://{{ inventory_hostname }}:8080 install-plugin {{ item }}
  ignore_errors: yes
  loop:
    - Locale
    - Git
    - Pipeline
  delegate_to: localhost
- name: Restart Jenkins
  shell: docker restart ec2-user_jenkins_master_1
