---
- name: Install Apache
  shell: docker run -d --name apache_web_server -p 80:80 httpd
- name: Generate default web page for web server
  template: src=index.j2 dest={{ default_web_page }} mode=0555
- name: Copy default web page to the container
  shell: docker cp {{ default_web_page }} apache_web_server:/usr/local/apache2/htdocs/index.html
