- name: Restart Apache web server for   RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"
- name: Restart Apache web server for Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
- name: Start and Enable Apache
  service: name=httpd state=started enabled=yes
