---
- name: Get initial password
  shell: docker exec -it ec2-user_jenkins_master_1 cat /var/jenkins_home/secrets/initialAdminPassword
  register: jenkins_initial_password
- debug:
    var: jenkins_initial_password.stdout
