---
- name: Install Docker
  yum: name=docker state=latest
- name: Start Docker
  service: name=docker state=restarted
- shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- shell: chmod +x /usr/local/bin/docker-compose
- shell: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  ignore_errors: yes
