#!/bin/bash

function mrip() {
	if [ -z $2 ]
	then
		cat $1 | awk '{print $1}' | sort | uniq -c | sort -nr |  awk 'BEGIN {print "\033[32mNN IP COUNT\033[0m"} {print FNR, $2, $1}' | column -t
	else
		cat $1 | awk '{print $1}' | sort | uniq -c | sort -nr | head -n $2 | awk 'BEGIN {print "\033[32mNN IP COUNT\033[0m"} {print FNR, $2, $1}' | column -t 
	fi
}

function mrpa() {
	if [ -z $2 ]
	then
		cat $1 | awk '{print $7}' | sort | uniq -c | sort -nr | awk 'BEGIN {print "\033[32mNN PAGE COUNT\033[0m"} {print FNR, $2, $1}' | column -t
	else
		cat $1 | awk '{print $7}' | sort | uniq -c | sort -nr | head -n $2 | awk 'BEGIN {print "\033[32mNN PAGE COUNT\033[0m"} {print FNR, $2, $1}' | column -t
	fi
}

function non_existent_pages_visited() {
        if [ -z $2 ]
        then
                cat $1 | grep error | awk '{print $1 $7}' | awk -F "/" '{print $1"\t"$2}' | sort | uniq -c | sort -nr | awk 'BEGIN {print "\033[32mNN IP ERROR COUNT\033[0m"} {print FNR, $2, $3, $1}' | column -t
        else
                cat $1 | grep error | awk '{print $1 $7}' | awk -F "/" '{print $1"\t"$2}' | sort | uniq -c | sort -nr | head -n $2 | awk 'BEGIN {print "\033[32mNN IP ERROR COUNT\033[0m"} {print FNR, $2, $3, $1}' | column -t
        fi
}

function mrt() {
	if [ -z $2 ]
        then
                cat $1 | awk '{print $4"]"}' | sort | uniq -c | sort -nr | awk 'BEGIN {print "\033[32mNN TIME COUNT\033[0m"} {print FNR, $2, $1}' | column -t
        else
		cat $1 | awk '{print $4"]"}' | sort | uniq -c | sort -nr | head -n $2 | awk 'BEGIN {print "\033[32mNN TIME COUNT\033[0m"} {print FNR, $2, $1}' | column -t        
	fi
}

function search_bot_request() {
	if [ -z $2 ]
        then
                cat $1 | grep bot | awk -F "\"" '{print $6}' | awk -F "//" '{print $2}' | awk 'NF' | awk -F ")" '{print $1}'  | sort | uniq -c | sort -nr | awk 'BEGIN {print "\033[32mNN BOT COUNT\033[0m"} {print FNR, $2, $1}' | column -t
        else
                cat $1 | grep bot | awk -F "\"" '{print $6}' | awk -F "//" '{print $2}' | awk 'NF' | awk -F ")" '{print $1}'  | sort | uniq -c | sort -nr | head -n $2 | awk 'BEGIN {print "\033[32mNN BOT COUNT\033[0m"} {print FNR, $2, $1}' | column -t
	fi
}

if [ "$#" == "0" ]
then
	echo -e "\033[31m$0""\033[0m has 5 keys:"
	echo "The --mrip the most requested IP adresses"
        echo "The --mrpa the most requested pages"
	echo "The --non-existent-pages-visited IP adresses that got error"
	echo "The --mrt the time site was most requested"
	echo "The --searchbot-request what searchbots requested the site"
	exit 0
elif [ -z $2 ]
then
        echo -e "ERROR. You have to choose an apache_log"
        exit 1
else
	log_name=$2
	search_size=$3
fi

case $1 in
	--mrip) mrip $log_name $search_size;;
        --mrpa) mrpa $log_name $search_size;;
        --non-existent-pages-visited) non_existent_pages_visited $log_name $search_size;;
	--mrt) mrt $log_name $search_size;;
        --search-bot-request) search_bot_request $log_name $search_size;;
	*) echo -e "There is\033[31m no \033[0m$1 key"
esac
exit 0
